language: c
compiler:
  - gcc
  - clang
install:
    - sudo apt-get -qq install gperf
before_script:
  - cd ../
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - cp -fp ../mruby-bnet-authenticator/.travis_build_config.rb build_config.rb
script:
  - "./minirake all test"
